"""add_admin_audit_log_notifications_bank_confirm

Revision ID: 12727c40ba86
Revises: b650666ac82b
Create Date: 2026-06-19 10:58:30.625018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12727c40ba86'
down_revision: Union[str, None] = 'b650666ac82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_organisation_id'), 'notifications', ['organisation_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_organisation_id'), 'audit_logs', ['organisation_id'], unique=False)
    op.add_column('subscription_payments', sa.Column('bank_confirmed', sa.Boolean(), nullable=False))
    op.add_column('subscription_payments', sa.Column('bank_confirmed_by', sa.String(length=32), nullable=True))
    op.add_column('subscription_payments', sa.Column('bank_confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('subscription_payments', 'bank_confirmed_at')
    op.drop_column('subscription_payments', 'bank_confirmed_by')
    op.drop_column('subscription_payments', 'bank_confirmed')
    op.drop_index(op.f('ix_audit_logs_organisation_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_notifications_organisation_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
