"""add_servicing_models

Revision ID: 3d6e86453878
Revises: 9522b1ecf6a2
Create Date: 2026-07-01 08:38:41.588745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6e86453878'
down_revision: Union[str, None] = '9522b1ecf6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_types',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interval_km', sa.Integer(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_types_organisation_id'), 'service_types', ['organisation_id'], unique=False)
    op.create_table('taxi_service_schedules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('taxi_id', sa.String(length=32), nullable=False),
    sa.Column('service_type_id', sa.String(length=32), nullable=False),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('last_service_km', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('next_due_km', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.ForeignKeyConstraint(['taxi_id'], ['taxis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxi_service_schedules_organisation_id'), 'taxi_service_schedules', ['organisation_id'], unique=False)
    op.create_table('service_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('taxi_id', sa.String(length=32), nullable=False),
    sa.Column('service_type_id', sa.String(length=32), nullable=False),
    sa.Column('schedule_id', sa.String(length=32), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('captured_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['taxi_service_schedules.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.ForeignKeyConstraint(['taxi_id'], ['taxis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_organisation_id'), 'service_records', ['organisation_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_service_records_organisation_id'), table_name='service_records')
    op.drop_table('service_records')
    op.drop_index(op.f('ix_taxi_service_schedules_organisation_id'), table_name='taxi_service_schedules')
    op.drop_table('taxi_service_schedules')
    op.drop_index(op.f('ix_service_types_organisation_id'), table_name='service_types')
    op.drop_table('service_types')
