"""phase3_fuel_route_route_assignment

Revision ID: a0b0bc4bc7d4
Revises: f2cc2df8e7ca
Create Date: 2026-06-18 13:20:58.217513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b0bc4bc7d4'
down_revision: Union[str, None] = 'f2cc2df8e7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_organisation_id'), 'routes', ['organisation_id'], unique=False)
    op.create_table('fuel',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('taxi_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('litres', sa.Float(), nullable=False),
    sa.Column('cost_total', sa.Integer(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('captured_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['taxi_id'], ['taxis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_organisation_id'), 'fuel', ['organisation_id'], unique=False)
    op.create_table('route_assignments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('daily_income_id', sa.String(length=32), nullable=False),
    sa.Column('route_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['daily_income_id'], ['daily_income.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_income_id')
    )
    op.create_index(op.f('ix_route_assignments_organisation_id'), 'route_assignments', ['organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_assignments_organisation_id'), table_name='route_assignments')
    op.drop_table('route_assignments')
    op.drop_index(op.f('ix_fuel_organisation_id'), table_name='fuel')
    op.drop_table('fuel')
    op.drop_index(op.f('ix_routes_organisation_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
