"""phase1_taxi_driver_income_breakdown_invite

Revision ID: f2cc2df8e7ca
Revises: a32de1369dcb
Create Date: 2026-06-18 13:02:01.314145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cc2df8e7ca'
down_revision: Union[str, None] = 'a32de1369dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxis',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'registration_number')
    )
    op.create_index(op.f('ix_taxis_organisation_id'), 'taxis', ['organisation_id'], unique=False)
    op.create_table('breakdowns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('taxi_id', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('cost_total', sa.Integer(), nullable=True),
    sa.Column('parts_used', sa.String(length=1000), nullable=True),
    sa.Column('captured_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['taxi_id'], ['taxis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakdowns_organisation_id'), 'breakdowns', ['organisation_id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('assigned_taxi_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_taxi_id'], ['taxis.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_organisation_id'), 'drivers', ['organisation_id'], unique=False)
    op.create_table('invite_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_tokens_organisation_id'), 'invite_tokens', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_invite_tokens_token'), 'invite_tokens', ['token'], unique=True)
    op.create_table('daily_income',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', sa.String(length=32), nullable=False),
    sa.Column('taxi_id', sa.String(length=32), nullable=False),
    sa.Column('driver_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_cash', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('captured_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['taxi_id'], ['taxis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'taxi_id', 'date')
    )
    op.create_index(op.f('ix_daily_income_organisation_id'), 'daily_income', ['organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_income_organisation_id'), table_name='daily_income')
    op.drop_table('daily_income')
    op.drop_index(op.f('ix_invite_tokens_token'), table_name='invite_tokens')
    op.drop_index(op.f('ix_invite_tokens_organisation_id'), table_name='invite_tokens')
    op.drop_table('invite_tokens')
    op.drop_index(op.f('ix_drivers_organisation_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_breakdowns_organisation_id'), table_name='breakdowns')
    op.drop_table('breakdowns')
    op.drop_index(op.f('ix_taxis_organisation_id'), table_name='taxis')
    op.drop_table('taxis')
    # ### end Alembic commands ###
